const School = require("../models/School");

const NIGERIAN_SCHOOLS = [
  // ── FEDERAL UNIVERSITIES ───────────────────────
  {
    name: "University of Lagos",
    shortName: "UniLag",
    acronym: "UNILAG",
    type: "federal-university",
    ownership: "federal",
    state: "Lagos",
    city: "Yaba",
    established: 1962,
    website: "https://unilag.edu.ng",
    description:
      "University of Lagos, popularly known as UniLag, is a federal research university located in Lagos, Nigeria. Established in 1962, it is one of the oldest and most prestigious universities in Nigeria.",
    motto: "In Lumine Tuo Videbimus Lumen",
    studentCount: "60,000+",
    jamb: {
      cutoffMark: 200,
      subjectCombo: ["English", "Mathematics", "Any two relevant subjects"],
    },
    postUtme: {
      hasExam: true,
      examFee: "₦2,000",
      examFormat: "CBT - Multiple choice",
    },
    schoolFees: {
      freshmen: "₦200,000–₦500,000",
      returning: "₦150,000–₦350,000",
    },
    faculties: [
      "Faculty of Arts",
      "Faculty of Business Administration",
      "Faculty of Education",
      "Faculty of Engineering",
      "Faculty of Environmental Sciences",
      "Faculty of Law",
      "Faculty of Medicine",
      "Faculty of Pharmacy",
      "Faculty of Science",
      "Faculty of Social Sciences",
    ],
    social: {
      twitter: "https://twitter.com/unilagofficial",
      facebook: "https://facebook.com/unilag",
      instagram: "https://instagram.com/unilag_official",
    },
    applicationPortal: "https://portal.unilag.edu.ng",
    isAccredited: true,
    isFeatured: true,
    tags: ["medicine", "engineering", "law", "business", "science"],
  },
  {
    name: "Obafemi Awolowo University",
    shortName: "OAU",
    acronym: "OAU",
    type: "federal-university",
    ownership: "federal",
    state: "Osun",
    city: "Ile-Ife",
    established: 1961,
    website: "https://oauife.edu.ng",
    description:
      "Obafemi Awolowo University (OAU), formerly University of Ife, is a federal research university located in Ile-Ife, Osun State. It is consistently ranked among the top universities in Nigeria.",
    motto: "For Learning and Culture",
    studentCount: "35,000+",
    jamb: {
      cutoffMark: 200,
      subjectCombo: ["English", "Mathematics", "Physics", "Chemistry"],
    },
    postUtme: {
      hasExam: true,
      examFee: "₦2,000",
      examFormat: "CBT - Multiple choice",
    },
    schoolFees: {
      freshmen: "₦100,000–₦250,000",
      returning: "₦80,000–₦180,000",
    },
    faculties: [
      "Faculty of Administration",
      "Faculty of Agriculture",
      "Faculty of Arts",
      "Faculty of Basic Medical Sciences",
      "Faculty of Clinical Sciences",
      "Faculty of Dentistry",
      "Faculty of Education",
      "Faculty of Environmental Design and Management",
      "Faculty of Law",
      "Faculty of Pharmacy",
      "Faculty of Science",
      "Faculty of Social Sciences",
      "Faculty of Technology",
    ],
    applicationPortal: "https://oauifesos.edu.ng",
    isAccredited: true,
    isFeatured: true,
    tags: ["medicine", "technology", "arts", "law", "science"],
  },
  {
    name: "University of Ibadan",
    shortName: "UI",
    acronym: "UI",
    type: "federal-university",
    ownership: "federal",
    state: "Oyo",
    city: "Ibadan",
    established: 1948,
    website: "https://ui.edu.ng",
    description:
      "University of Ibadan is the oldest university in Nigeria, established in 1948. It is a premier research institution and has produced many of Nigeria's foremost leaders, scholars, and professionals.",
    motto: "Illumination, Knowledge and Integrity",
    studentCount: "30,000+",
    jamb: {
      cutoffMark: 200,
      subjectCombo: ["English", "Mathematics", "Any two relevant subjects"],
    },
    postUtme: { hasExam: true, examFee: "₦2,500" },
    schoolFees: { freshmen: "₦80,000–₦200,000", returning: "₦60,000–₦150,000" },
    faculties: [
      "Faculty of Agriculture and Forestry",
      "Faculty of Arts",
      "Faculty of Basic Medical Sciences",
      "Faculty of Clinical Sciences",
      "Faculty of Dentistry",
      "Faculty of Education",
      "Faculty of Law",
      "Faculty of Pharmacy",
      "Faculty of Public Health",
      "Faculty of Science",
      "Faculty of Social Sciences",
      "Faculty of Technology",
      "Faculty of Veterinary Medicine",
    ],
    applicationPortal: "https://admissions.ui.edu.ng",
    isAccredited: true,
    isFeatured: true,
    tags: ["medicine", "law", "science", "arts", "veterinary"],
  },
  {
    name: "Ahmadu Bello University",
    shortName: "ABU",
    acronym: "ABU",
    type: "federal-university",
    ownership: "federal",
    state: "Kaduna",
    city: "Zaria",
    established: 1962,
    website: "https://abu.edu.ng",
    description:
      "Ahmadu Bello University (ABU) is a federal research university located in Zaria, Kaduna State. It is one of the largest universities in Africa by student enrollment.",
    motto: "Achievement, Belief, Unity",
    studentCount: "80,000+",
    jamb: {
      cutoffMark: 160,
      subjectCombo: ["English", "Mathematics", "Any two relevant subjects"],
    },
    postUtme: { hasExam: true, examFee: "₦2,000" },
    schoolFees: { freshmen: "₦90,000–₦200,000", returning: "₦70,000–₦150,000" },
    faculties: [
      "Faculty of Administration",
      "Faculty of Agriculture",
      "Faculty of Allied Health Sciences",
      "Faculty of Arts",
      "Faculty of Basic Clinical Sciences",
      "Faculty of Education",
      "Faculty of Engineering",
      "Faculty of Environmental Design",
      "Faculty of Law",
      "Faculty of Medicine",
      "Faculty of Pharmaceutical Sciences",
      "Faculty of Science",
      "Faculty of Social Sciences",
      "Faculty of Veterinary Medicine",
    ],
    isAccredited: true,
    isFeatured: true,
    tags: ["engineering", "medicine", "agriculture", "law"],
  },
  {
    name: "University of Nigeria, Nsukka",
    shortName: "UNN",
    acronym: "UNN",
    type: "federal-university",
    ownership: "federal",
    state: "Enugu",
    city: "Nsukka",
    established: 1960,
    website: "https://unn.edu.ng",
    description:
      "University of Nigeria, Nsukka (UNN) is the first fully indigenous university in Nigeria, founded by Dr. Nnamdi Azikiwe in 1960. It is located in Nsukka, Enugu State.",
    motto: "To Restore the Dignity of Man",
    studentCount: "40,000+",
    jamb: {
      cutoffMark: 180,
      subjectCombo: ["English", "Mathematics", "Any two relevant subjects"],
    },
    postUtme: { hasExam: true, examFee: "₦2,000" },
    schoolFees: {
      freshmen: "₦100,000–₦220,000",
      returning: "₦80,000–₦180,000",
    },
    faculties: [
      "Faculty of Agriculture",
      "Faculty of Arts",
      "Faculty of Bio-Resources and Food Technology",
      "Faculty of Business Administration",
      "Faculty of Education",
      "Faculty of Engineering",
      "Faculty of Environmental Studies",
      "Faculty of Law",
      "Faculty of Medical Sciences",
      "Faculty of Pharmaceutical Sciences",
      "Faculty of Physical Sciences",
      "Faculty of Social Sciences",
      "Faculty of Veterinary Medicine",
    ],
    isAccredited: true,
    isFeatured: true,
    tags: ["medicine", "engineering", "law", "agriculture"],
  },
  {
    name: "Ladoke Akintola University of Technology",
    shortName: "LAUTECH",
    acronym: "LAUTECH",
    type: "state-university",
    ownership: "state",
    state: "Oyo",
    city: "Ogbomoso",
    established: 1990,
    website: "https://lautech.edu.ng",
    description:
      "Ladoke Akintola University of Technology (LAUTECH) is a state university located in Ogbomoso, Oyo State. It is jointly owned by Oyo and Osun states and is known for its strong engineering and technology programmes.",
    motto: "Knowledge, Excellence, Service",
    studentCount: "25,000+",
    jamb: {
      cutoffMark: 180,
      subjectCombo: ["English", "Mathematics", "Physics", "Chemistry"],
    },
    postUtme: { hasExam: true, examFee: "₦2,000", examFormat: "CBT" },
    schoolFees: {
      freshmen: "₦150,000–₦350,000",
      returning: "₦120,000–₦280,000",
    },
    faculties: [
      "College of Engineering",
      "College of Pure and Applied Sciences",
      "College of Agricultural Sciences",
      "College of Clinical Sciences",
      "College of Basic Medical Sciences",
      "College of Management Sciences",
      "College of Education",
    ],
    isAccredited: true,
    tags: ["engineering", "technology", "medicine", "science"],
  },
  {
    name: "Federal University of Technology, Akure",
    shortName: "FUTA",
    acronym: "FUTA",
    type: "federal-university",
    ownership: "federal",
    state: "Ondo",
    city: "Akure",
    established: 1981,
    website: "https://futa.edu.ng",
    description:
      "Federal University of Technology, Akure (FUTA) is a federal research university located in Akure, Ondo State. It specializes in technology and applied sciences.",
    motto: "Technology for Self-Reliance",
    studentCount: "20,000+",
    jamb: {
      cutoffMark: 180,
      subjectCombo: ["English", "Mathematics", "Physics", "Chemistry"],
    },
    postUtme: { hasExam: true, examFee: "₦2,000" },
    schoolFees: { freshmen: "₦90,000–₦180,000", returning: "₦70,000–₦140,000" },
    faculties: [
      "School of Agriculture and Agricultural Technology",
      "School of Bio-Technology",
      "School of Earth and Mineral Sciences",
      "School of Engineering and Engineering Technology",
      "School of Environmental Technology",
      "School of Health and Health Technology",
      "School of Management Technology",
      "School of Sciences",
    ],
    isAccredited: true,
    tags: ["engineering", "technology", "science", "agriculture"],
  },
  {
    name: "Nnamdi Azikiwe University",
    shortName: "UNIZIK",
    acronym: "UNIZIK",
    type: "federal-university",
    ownership: "federal",
    state: "Anambra",
    city: "Awka",
    established: 1992,
    website: "https://unizik.edu.ng",
    description:
      "Nnamdi Azikiwe University (UNIZIK) is a federal university located in Awka, Anambra State. Named after Nigeria's first president, it is one of the prominent federal universities in southeastern Nigeria.",
    studentCount: "30,000+",
    jamb: { cutoffMark: 180 },
    postUtme: { hasExam: true, examFee: "₦2,000" },
    schoolFees: {
      freshmen: "₦100,000–₦250,000",
      returning: "₦80,000–₦200,000",
    },
    faculties: [
      "Faculty of Agriculture",
      "Faculty of Arts",
      "Faculty of Education",
      "Faculty of Engineering",
      "Faculty of Environmental Sciences",
      "Faculty of Health Sciences & Technology",
      "Faculty of Law",
      "Faculty of Medicine",
      "Faculty of Pharmacy",
      "Faculty of Science",
      "Faculty of Social Sciences",
    ],
    isAccredited: true,
    tags: ["medicine", "engineering", "law", "science"],
  },
  {
    name: "University of Benin",
    shortName: "UNIBEN",
    acronym: "UNIBEN",
    type: "federal-university",
    ownership: "federal",
    state: "Edo",
    city: "Benin City",
    established: 1970,
    website: "https://uniben.edu.ng",
    description:
      "University of Benin (UNIBEN) is a federal university located in Benin City, Edo State. It is known for its strong programmes in medicine, law, engineering and the social sciences.",
    studentCount: "40,000+",
    jamb: { cutoffMark: 180 },
    postUtme: { hasExam: true, examFee: "₦2,000" },
    schoolFees: {
      freshmen: "₦120,000–₦280,000",
      returning: "₦90,000–₦200,000",
    },
    faculties: [
      "Faculty of Agriculture",
      "Faculty of Arts",
      "Faculty of Basic Medical Sciences",
      "Faculty of Clinical Sciences",
      "Faculty of Dentistry",
      "Faculty of Education",
      "Faculty of Engineering",
      "Faculty of Environmental Sciences",
      "Faculty of Law",
      "Faculty of Pharmacy",
      "Faculty of Science",
      "Faculty of Social Sciences",
    ],
    isAccredited: true,
    isFeatured: true,
    tags: ["medicine", "law", "engineering", "pharmacy"],
  },
  {
    name: "University of Port Harcourt",
    shortName: "UNIPORT",
    acronym: "UNIPORT",
    type: "federal-university",
    ownership: "federal",
    state: "Rivers",
    city: "Port Harcourt",
    established: 1975,
    website: "https://uniport.edu.ng",
    description:
      "University of Port Harcourt (UniPort) is a federal university located in Port Harcourt, Rivers State. It is known for its strong programmes in petroleum engineering and environmental sciences.",
    studentCount: "35,000+",
    jamb: { cutoffMark: 180 },
    postUtme: { hasExam: true, examFee: "₦2,000" },
    schoolFees: {
      freshmen: "₦100,000–₦230,000",
      returning: "₦80,000–₦180,000",
    },
    faculties: [
      "Faculty of Agriculture",
      "Faculty of Arts",
      "Faculty of Education",
      "Faculty of Engineering",
      "Faculty of Management Sciences",
      "Faculty of Medicine",
      "Faculty of Pharmacy",
      "Faculty of Pharmacy",
      "Faculty of Science",
      "Faculty of Social Sciences",
    ],
    isAccredited: true,
    tags: ["engineering", "petroleum", "medicine", "science"],
  },
  {
    name: "Covenant University",
    shortName: "CU",
    acronym: "CU",
    type: "private-university",
    ownership: "private",
    state: "Ogun",
    city: "Ota",
    established: 2002,
    website: "https://covenantuniversity.edu.ng",
    description:
      "Covenant University is a private Christian university located in Ota, Ogun State. It is consistently ranked as the best private university and one of the top universities in Nigeria and Africa.",
    motto: "Raising a New Generation of Leaders",
    studentCount: "10,000+",
    jamb: { cutoffMark: 200 },
    postUtme: { hasExam: true },
    schoolFees: {
      freshmen: "₦800,000–₦2,000,000",
      returning: "₦700,000–₦1,500,000",
    },
    faculties: [
      "College of Business and Social Sciences",
      "College of Engineering",
      "College of Leadership Development Studies",
      "College of Science and Technology",
    ],
    isAccredited: true,
    isFeatured: true,
    tags: ["engineering", "business", "technology", "private"],
  },
  {
    name: "Babcock University",
    shortName: "BU",
    acronym: "BABCOCK",
    type: "private-university",
    ownership: "private",
    state: "Ogun",
    city: "Ilishan-Remo",
    established: 1999,
    website: "https://babcock.edu.ng",
    description:
      "Babcock University is a private Adventist university located in Ilishan-Remo, Ogun State. It is one of Nigeria's leading private universities known for academic excellence.",
    studentCount: "12,000+",
    jamb: { cutoffMark: 180 },
    postUtme: { hasExam: true },
    schoolFees: {
      freshmen: "₦700,000–₦1,500,000",
      returning: "₦600,000–₦1,200,000",
    },
    faculties: [
      "College of Health and Medical Sciences",
      "College of Law and Security Studies",
      "College of Management and Social Sciences",
      "College of Natural and Applied Sciences",
      "School of Education and Humanities",
    ],
    isAccredited: true,
    tags: ["medicine", "law", "science", "private"],
  },
  {
    name: "Bayero University Kano",
    shortName: "BUK",
    acronym: "BUK",
    type: "federal-university",
    ownership: "federal",
    state: "Kano",
    city: "Kano",
    established: 1975,
    website: "https://buk.edu.ng",
    description:
      "Bayero University Kano (BUK) is a federal university located in Kano. It is one of the leading universities in Northern Nigeria and a major centre for Islamic studies.",
    studentCount: "40,000+",
    jamb: { cutoffMark: 160 },
    postUtme: { hasExam: true },
    schoolFees: { freshmen: "₦80,000–₦180,000", returning: "₦60,000–₦140,000" },
    faculties: [
      "Faculty of Agriculture",
      "Faculty of Arts and Islamic Studies",
      "Faculty of Clinical Sciences",
      "Faculty of Computer Science and Information Technology",
      "Faculty of Education",
      "Faculty of Engineering",
      "Faculty of Law",
      "Faculty of Management Sciences",
      "Faculty of Medicine",
      "Faculty of Science",
    ],
    isAccredited: true,
    tags: ["medicine", "engineering", "law", "islamic studies"],
  },
  {
    name: "Federal University of Technology, Minna",
    shortName: "FUT Minna",
    acronym: "FUTMINNA",
    type: "federal-university",
    ownership: "federal",
    state: "Niger",
    city: "Minna",
    established: 1983,
    website: "https://futminna.edu.ng",
    description:
      "Federal University of Technology, Minna (FUTMINNA) is a federal technology university located in Minna, Niger State. It focuses on science, engineering and technology programmes.",
    studentCount: "20,000+",
    jamb: { cutoffMark: 160 },
    postUtme: { hasExam: true },
    schoolFees: { freshmen: "₦85,000–₦180,000", returning: "₦65,000–₦140,000" },
    faculties: [
      "School of Agriculture and Agricultural Technology",
      "School of Engineering and Engineering Technology",
      "School of Environmental Technology",
      "School of Information and Communication Technology",
      "School of Science and Science Education",
    ],
    isAccredited: true,
    tags: ["engineering", "technology", "science", "agriculture"],
  },
  {
    name: "Imo State University",
    shortName: "IMSU",
    acronym: "IMSU",
    type: "state-university",
    ownership: "state",
    state: "Imo",
    city: "Owerri",
    established: 1981,
    website: "https://imsu.edu.ng",
    description:
      "Imo State University (IMSU) is a state university located in Owerri, Imo State. It is one of the leading state universities in southeastern Nigeria.",
    studentCount: "20,000+",
    jamb: { cutoffMark: 160 },
    postUtme: { hasExam: true },
    schoolFees: {
      freshmen: "₦120,000–₦280,000",
      returning: "₦90,000–₦200,000",
    },
    faculties: [
      "Faculty of Agriculture and Veterinary Medicine",
      "Faculty of Arts",
      "Faculty of Business Administration",
      "Faculty of Education",
      "Faculty of Engineering",
      "Faculty of Environmental Sciences",
      "Faculty of Law",
      "Faculty of Sciences",
      "Faculty of Social Sciences",
    ],
    isAccredited: true,
    tags: ["engineering", "law", "medicine", "science"],
  },
  {
    name: "Lagos State University",
    shortName: "LASU",
    acronym: "LASU",
    type: "state-university",
    ownership: "state",
    state: "Lagos",
    city: "Ojo",
    established: 1983,
    website: "https://lasu.edu.ng",
    description:
      "Lagos State University (LASU) is a state university located in Ojo, Lagos State. It is the largest state university in Lagos and one of the most attended universities in Nigeria.",
    studentCount: "50,000+",
    jamb: { cutoffMark: 180 },
    postUtme: { hasExam: true, examFee: "₦2,000" },
    schoolFees: {
      freshmen: "₦100,000–₦250,000",
      returning: "₦80,000–₦200,000",
    },
    faculties: [
      "College of Medicine",
      "Faculty of Agriculture",
      "Faculty of Arts",
      "Faculty of Business and Management Sciences",
      "Faculty of Education",
      "Faculty of Engineering",
      "Faculty of Environmental Sciences",
      "Faculty of Law",
      "Faculty of Science",
    ],
    isAccredited: true,
    isFeatured: true,
    tags: ["medicine", "engineering", "law", "science"],
  },
  {
    name: "Ambrose Alli University",
    shortName: "AAU",
    acronym: "AAU",
    type: "state-university",
    ownership: "state",
    state: "Edo",
    city: "Ekpoma",
    established: 1980,
    website: "https://aauekpoma.edu.ng",
    description:
      "Ambrose Alli University (AAU) is a state university located in Ekpoma, Edo State. It is one of the prominent state universities in southern Nigeria.",
    studentCount: "25,000+",
    jamb: { cutoffMark: 160 },
    postUtme: { hasExam: true },
    schoolFees: {
      freshmen: "₦100,000–₦220,000",
      returning: "₦80,000–₦180,000",
    },
    faculties: [
      "Faculty of Agriculture",
      "Faculty of Arts and Education",
      "Faculty of Basic Medical Sciences",
      "Faculty of Clinical Sciences",
      "Faculty of Engineering",
      "Faculty of Law",
      "Faculty of Natural Science",
      "Faculty of Pharmacy",
      "Faculty of Social and Management Sciences",
    ],
    isAccredited: true,
    tags: ["medicine", "engineering", "law", "pharmacy"],
  },
  {
    name: "Pan-Atlantic University",
    shortName: "PAU",
    acronym: "PAU",
    type: "private-university",
    ownership: "private",
    state: "Lagos",
    city: "Ibeju-Lekki",
    established: 2002,
    website: "https://pau.edu.ng",
    description:
      "Pan-Atlantic University (PAU) is a private university in Lagos, known for its Lagos Business School — one of the top business schools in Africa.",
    studentCount: "3,000+",
    jamb: { cutoffMark: 200 },
    postUtme: { hasExam: true },
    schoolFees: {
      freshmen: "₦1,500,000–₦3,000,000",
      returning: "₦1,200,000–₦2,500,000",
    },
    faculties: [
      "Lagos Business School",
      "School of Media and Communication",
      "School of Science and Technology",
    ],
    isAccredited: true,
    tags: ["business", "mba", "media", "private"],
  },
  // ── POLYTECHNICS ────────────────────────────────
  {
    name: "Yaba College of Technology",
    shortName: "Yabatech",
    acronym: "YABATECH",
    type: "federal-polytechnic",
    ownership: "federal",
    state: "Lagos",
    city: "Yaba",
    established: 1947,
    website: "https://yabatech.edu.ng",
    description:
      "Yaba College of Technology (Yabatech) is a federal polytechnic located in Yaba, Lagos. It is the oldest technical institution in Nigeria and one of the most prestigious polytechnics in West Africa.",
    motto: "Technology for Development",
    studentCount: "30,000+",
    jamb: { cutoffMark: 120 },
    postUtme: { hasExam: true, examFee: "₦1,500" },
    schoolFees: { freshmen: "₦80,000–₦150,000", returning: "₦60,000–₦120,000" },
    faculties: [
      "School of Art, Design and Printing",
      "School of Business and Office Technology",
      "School of Engineering",
      "School of Environmental Studies",
      "School of Management and Business Studies",
      "School of Pure and Applied Sciences",
      "School of Technology",
    ],
    isAccredited: true,
    isFeatured: true,
    tags: ["engineering", "technology", "art", "design"],
  },
  {
    name: "Federal Polytechnic Nekede",
    shortName: "Fed Poly Nekede",
    acronym: "NEKEDE",
    type: "federal-polytechnic",
    ownership: "federal",
    state: "Imo",
    city: "Nekede",
    established: 1978,
    website: "https://fpno.edu.ng",
    description:
      "Federal Polytechnic Nekede is a federal polytechnic located in Nekede, Imo State. It offers ND and HND programmes in various engineering and applied sciences.",
    jamb: { cutoffMark: 100 },
    postUtme: { hasExam: false },
    schoolFees: { freshmen: "₦50,000–₦100,000", returning: "₦40,000–₦80,000" },
    faculties: [
      "School of Business Studies",
      "School of Engineering Technology",
      "School of Environmental Studies",
      "School of Industrial Science",
      "School of Information and Communication Technology",
    ],
    isAccredited: true,
    tags: ["engineering", "technology", "ict", "polytechnic"],
  },
  {
    name: "The Polytechnic Ibadan",
    shortName: "Poly Ibadan",
    acronym: "POLYIBADAN",
    type: "state-polytechnic",
    ownership: "state",
    state: "Oyo",
    city: "Ibadan",
    established: 1970,
    website: "https://polyibadan.edu.ng",
    description:
      "The Polytechnic, Ibadan is a state polytechnic located in Ibadan, Oyo State. It is one of the leading polytechnics in southwestern Nigeria.",
    jamb: { cutoffMark: 100 },
    postUtme: { hasExam: false },
    schoolFees: { freshmen: "₦60,000–₦120,000", returning: "₦50,000–₦100,000" },
    faculties: [
      "School of Applied Sciences",
      "School of Business Studies",
      "School of Engineering",
      "School of Environmental Studies",
      "School of Information and Communication Technology",
    ],
    isAccredited: true,
    tags: ["engineering", "business", "ict", "polytechnic"],
  },
  // ── COLLEGES OF EDUCATION ───────────────────────
  {
    name: "Federal College of Education, Abeokuta",
    shortName: "FCE Abeokuta",
    acronym: "FCEABEOKUTA",
    type: "college-of-education",
    ownership: "federal",
    state: "Ogun",
    city: "Abeokuta",
    established: 1976,
    website: "https://fceabeokuta.edu.ng",
    description:
      "Federal College of Education, Abeokuta is a federal college of education in Ogun State, offering NCE programmes across various teaching specializations.",
    jamb: { cutoffMark: 100 },
    postUtme: { hasExam: false },
    schoolFees: { freshmen: "₦40,000–₦80,000", returning: "₦30,000–₦60,000" },
    faculties: [
      "School of Arts and Social Sciences",
      "School of Education",
      "School of Languages",
      "School of Sciences",
      "School of Vocational and Technical Education",
    ],
    isAccredited: true,
    tags: ["education", "nce", "teaching", "college"],
  },
  {
    name: "Adeniran Ogunsanya College of Education",
    shortName: "AOCOED",
    acronym: "AOCOED",
    type: "college-of-education",
    ownership: "state",
    state: "Lagos",
    city: "Ijanikin",
    established: 1982,
    website: "https://aocoed.edu.ng",
    description:
      "Adeniran Ogunsanya College of Education (AOCOED) is a state college of education in Lagos, offering NCE and degree programmes in partnership with universities.",
    jamb: { cutoffMark: 100 },
    postUtme: { hasExam: false },
    schoolFees: { freshmen: "₦50,000–₦100,000", returning: "₦40,000–₦80,000" },
    faculties: [
      "School of Arts and Social Sciences",
      "School of Business Education",
      "School of Early Childhood Education",
      "School of Languages",
      "School of Sciences",
      "School of Vocational Education",
    ],
    isAccredited: true,
    tags: ["education", "nce", "teaching", "lagos"],
  },
];

module.exports = async function seedSchools() {
  try {
    const count = await School.countDocuments();
    if (count > 0) {
      console.log(`✅ Schools already seeded (${count} schools in database)`);
      return;
    }

    console.log("🏫 Seeding Nigerian schools...");
    let seeded = 0;

    for (const schoolData of NIGERIAN_SCHOOLS) {
      try {
        await School.create(schoolData);
        seeded++;
        console.log(`  ✅ ${schoolData.name}`);
      } catch (err) {
        if (err.code !== 11000) {
          console.warn(`  ⚠️ Failed: ${schoolData.name} — ${err.message}`);
        }
      }
    }

    console.log(`\n🎉 Seeded ${seeded} Nigerian schools successfully!`);
  } catch (err) {
    console.error("School seeding error:", err.message);
  }
};
